# Install the latest version
telegraf_agent_package_state: latest

# Configure the output to point to an InfluxDB
# running on localhost, and # place data in the
# database "telegraf" which will be created if need be.
telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["http://127.0.0.1:8086"]
    - database = "telegraf"

# The default plugins, applied to any telegraf-configured host
telegraf_plugins_default:
  - plugin: cpu
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat

