---
# PostgreSQL
postgresql_objects_users:
  - name: "{{ galaxy_user_name }}"
  - name: telegraf
    password: null

# And this to grant telegraf privileges to
# SELECT values from the Galaxy database
postgresql_objects_privileges:
  - database: "{{ galaxy_db_name }}"
    roles: telegraf
    privs: SELECT
    objs: ALL_IN_SCHEMA

postgresql_objects_databases:
  - name: "{{ galaxy_db_name }}"
    owner: "{{ galaxy_user_name }}"

# PostgreSQL Backups
# Set this to a directory where your database will be backed up (this can be any format supported by rsync, e.g. user@host:/path).
# The most recent backup will be in a subdirectory named current.
# postgresql_backup_dir: ldelisle@jed.epfl.ch:/work/updub/backups_galaxyDB_since20240220_new
# Make a local copy of the backup dir:
postgresql_backup_dir: /data/backups_galaxyDB
# Boolean, defaults to true, which will cause the current directory to be renamed prior to creating a new backup.
# If set to false, current will be deleted (this is useful if you are using snapshots or some other means to archive previous backups).
postgresql_backup_rotate: false
# Do not back up everyday but every week:
# postgresql_backup_weekday: 0

# Useful for ubuntu
postgresql_backup_python_executable: "python3"

# This is not used anymore:
# User or address that should receive mail from the backup scripts.
# postgresql_backup_mail_recipient: lucille.delisle@epfl.ch
