---
- hosts: galaxyservers
  become: true
  vars_files:
    - secret_group_vars/all.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['acl', 'git', 'make', 'virtualenv', 'python3-psycopg2', 'tar', 'bzip2']
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - usegalaxy_eu.galaxy_systemd
    - galaxyproject.nginx
    - galaxyproject.proftpd
    - dj-wasabi.telegraf
    - galaxyproject.gxadmin
  post_tasks:
    - name: Setup gxadmin cleanup task
      ansible.builtin.cron:
        name: "Cleanup Old User Data"
        user: galaxy # Run as the Galaxy user
        minute: "0"
        hour: "0"
        job: "SHELL=/bin/bash source {{ galaxy_venv_dir }}/bin/activate &&  GALAXY_LOG_DIR=/tmp/gxadmin/ GALAXY_ROOT={{ galaxy_root }}/server GALAXY_CONFIG_FILE={{ galaxy_config_file }} /usr/local/bin/gxadmin galaxy cleanup 60"
