---
- src: galaxyproject.galaxy
  version: 0.10.14
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: galaxyproject.gxadmin
  version: 0.0.12
- src: galaxyproject.repos
  version: 0.0.3
- src: galaxyproject.slurm
  version: 1.0.2
- src: usegalaxy_eu.influxdb
  version: v6.0.7
- name: dj-wasabi.telegraf
  src: https://github.com/dj-wasabi/ansible-telegraf
  version: 6f6fdf7f5ead491560783d52528b79e9e088bd5b
- src: cloudalchemy.grafana
  version: 0.14.2
- src: galaxyproject.proftpd
  version: 0.3.1
