---
- src: galaxyproject.galaxy
  version: 0.9.7
- src: galaxyproject.nginx
  version: 0.6.4
- src: galaxyproject.proftpd
  version: 0.3.1
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.4
- src: galaxyproject.repos
  version: 0.0.2
- src: galaxyproject.slurm
  version: 0.1.3
- src: usegalaxy_eu.influxdb
  version: v6.0.3
- src: cloudalchemy.grafana
  version: 0.14.2
- src: dj-wasabi.telegraf
  version: 0.12.0
- src: usegalaxy_eu.gxadmin
  version: 0.0.6
