- hosts: galaxyservers
  become: true
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
  post_tasks:
    - name: Install slurm-drmaa1 if Debian
      package:
        name: slurm-drmaa1
      when: ansible_os_family == "Debian"
    - name: Install slurm-drmaa if RedHat
      package:
        name: slurm-drmaa
      when: ansible_os_family == "RedHat"
        
