{
 "title": "main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "disk usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"user-disk-usage\")\n   |> filter(fn: (r) => r._field == \"size\")\n   |> group(columns: [\"username\"])\n   |> last()\n   |> filter(fn: (r) => r._value > 20)\n   |> keep(columns: [\"_time\", \"_value\", \"username\"])"
    }
   ]
  },
  {
   "title": "Galaxy Queued Jobs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"queue-overview\")\n   |> filter(fn: (r) => r.state == \"queued\")\n   |> aggregateWindow(fn: max, every: v.windowPeriod)\n   |> keep(columns: [\"_time\", \"_value\", \"count\", \"tool_id\"])"
    }
   ]
  },
  {
   "title": "Galaxy Running Tools",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> aggregateWindow(fn: max, every: v.windowPeriod)\n   |> filter(fn: (r) => r._measurement == \"queue-overview\")\n   |> filter(fn: (r) => r.state == \"running\")\n   |> keep(columns: [\"_time\", \"_value\", \"count\", \"tool_id\"])"
    }
   ]
  }
 ]
}