{
 "title": "MEM_CPU_Disk",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "MEM usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> aggregateWindow(fn: mean, every: v.windowPeriod)\n   |> filter(fn: (r) => r._measurement == \"mem\")\n   |> filter(fn: (r) => r._field == \"used_percent\")"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"disk\")\n   |> filter(fn: (r) => r._field == \"used_percent\")\n   |> group(columns: [\"path\"])\n   |> keep(columns: [\"path\", \"_value\"])\n   |> last()"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> aggregateWindow(fn: mean, every: v.windowPeriod)\n   |> filter(fn: (r) => r._measurement == \"cpu\")\n   |> filter(fn: (r) => r.cpu == \"cpu-total\")\n   |> filter(fn: (r) => r._field == \"usage_user\")"
    }
   ]
  },
  {
   "title": "CPU usage each CPU overlayed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> aggregateWindow(fn: mean, every: v.windowPeriod)\n   |> filter(fn: (r) => r._measurement == \"cpu\")\n   |> filter(fn: (r) => r.cpu != \"cpu-total\")\n   |> filter(fn: (r) => r._field == \"usage_user\")\n   |> keep(columns: [\"_time\", \"_value\", \"cpu\"])"
    }
   ]
  }
 ]
}